# Generated by Django 4.2.7 on 2023-12-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='roll',
            field=models.IntegerField(default=1),
        ),
    ]
